apiVersion: v1
kind: Secret
metadata:
  name: ornn-api-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  NYXID_CLIENT_ID: "${NYXID_CLIENT_ID}"
  NYXID_CLIENT_SECRET: "${NYXID_CLIENT_SECRET}"
  MONGODB_URI: "${MONGODB_URI}"
