apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  MONGO_INITDB_DATABASE: ${MONGO_INIT_DB}
