apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  STS_USER: ${MINIO_STS_USER}
  STS_PASSWORD: ${MINIO_STS_PASSWORD}
