/**
 * OpenAPI contract tests (#462).
 *
 * CONVENTIONS.md §10 + §11.7: "every handler in code appears in the
 * spec with complete metadata". This test pins the structural
 * properties of the spec generated by `buildSpec()` so that:
 *
 *   1. The spec never silently regresses to a state where a declared
 *      path has no methods, or a method has no responses / tags.
 *   2. Adding a new path to the spec without a tag / response / summary
 *      fails CI immediately rather than landing as a half-documented
 *      endpoint.
 *   3. Error-response declarations (4xx / 5xx) carry the
 *      `application/problem+json` content type from #456 — anyone
 *      reverting that wire shape gets a test failure.
 *
 * Out of scope for this PR (tracked as follow-ups on #462):
 *   - Reflection over the live Hono app to assert every registered
 *     route has a spec entry. The current spec covers ~12 of the ~50
 *     real routes; closing that gap is a separate, larger sweep that
 *     needs each missing route to land with its own per-route schema.
 *   - Cross-checking declared error codes against handler `throw`
 *     statements — needs a code-walker, also follow-up.
 *
 * This test enforces what the spec already promises. The coverage
 * gap stays open as #462a until someone documents the missing routes.
 *
 * @module tests/contract/openapi
 */

import { describe, expect, test } from "bun:test";
import { buildSpec } from "../../src/openapi/specBuilder";

/**
 * Deployment-specific values `buildSpec` now takes as arguments (#1213).
 * Fixed here so assertions are about spec structure, not about whatever
 * the ambient environment happens to be.
 */
const SPEC_OPTIONS = { serverUrl: "https://api.test.invalid", version: "1.2.3" } as const;

type Spec = ReturnType<typeof buildSpec>;
type PathItem = Record<string, unknown>;
type Operation = {
  summary?: string;
  operationId?: string;
  tags?: string[];
  responses?: Record<string, unknown>;
  security?: unknown[];
  requestBody?: unknown;
};

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"] as const;
type HttpMethod = (typeof HTTP_METHODS)[number];

function isOperation(method: string): method is HttpMethod {
  return (HTTP_METHODS as readonly string[]).includes(method);
}

function eachOperation(
  spec: Spec,
  fn: (path: string, method: HttpMethod, op: Operation) => void,
): void {
  const paths = spec.paths as Record<string, PathItem>;
  for (const [path, pathItem] of Object.entries(paths)) {
    for (const [method, op] of Object.entries(pathItem)) {
      if (!isOperation(method)) continue;
      fn(path, method, op as Operation);
    }
  }
}

describe("OpenAPI spec — structural integrity (#462)", () => {
  const spec = buildSpec(SPEC_OPTIONS);

  test("spec is OpenAPI 3.1", () => {
    expect(spec.openapi).toBe("3.1.0");
  });

  test("spec declares title, version, description", () => {
    const info = spec.info as { title: string; version: string; description: string };
    expect(info.title).toBeTruthy();
    expect(info.version).toMatch(/^\d+\.\d+\.\d+/);
    expect(info.description.length).toBeGreaterThan(50);
  });

  test("spec has at least one server URL", () => {
    const servers = spec.servers as Array<{ url: string }>;
    expect(servers.length).toBeGreaterThan(0);
    expect(servers[0]!.url).toMatch(/^https?:\/\//);
  });

  test("server URL and version come from the caller, not the builder", () => {
    // Both were hardcoded until #1213 — `http://localhost:3802` and a
    // frozen `"2.0.0"` — so the published spec advertised a server no
    // client could reach and a version that never moved.
    expect((spec.servers as Array<{ url: string }>)[0]!.url).toBe(SPEC_OPTIONS.serverUrl);
    expect((spec.info as { version: string }).version).toBe(SPEC_OPTIONS.version);
  });

  test("BearerAuth security scheme is declared", () => {
    const components = spec.components as { securitySchemes: Record<string, unknown> };
    expect(components.securitySchemes.BearerAuth).toBeDefined();
  });

  test("every declared path carries the /api/v1 mount prefix", () => {
    // The spec's path table is hand-maintained while the router lives in
    // `bootstrap.ts`. They drifted once already: the spec published
    // `/api/*` for months after the router moved to `/api/v1/*` in #101,
    // so every URL NyxID rendered from this spec was wrong. CONVENTIONS.md
    // §3 makes `/api/v1/` normative — pin it here so a stale prefix fails
    // fast, without needing a booted app.
    const offenders = Object.keys(spec.paths as Record<string, unknown>)
      .filter((p) => !p.startsWith("/api/v1/"));
    expect(offenders).toEqual([]);
  });

  test("every declared path has at least one HTTP method", () => {
    const orphans: string[] = [];
    const paths = spec.paths as Record<string, PathItem>;
    for (const [path, pathItem] of Object.entries(paths)) {
      const methods = Object.keys(pathItem).filter(isOperation);
      if (methods.length === 0) orphans.push(path);
    }
    expect(orphans).toEqual([]);
  });
});

describe("OpenAPI spec — per-operation metadata (#462)", () => {
  const spec = buildSpec(SPEC_OPTIONS);

  test("every operation declares at least one tag", () => {
    const violations: string[] = [];
    eachOperation(spec, (path, method, op) => {
      if (!op.tags || op.tags.length === 0) {
        violations.push(`${method.toUpperCase()} ${path}`);
      }
    });
    expect(violations).toEqual([]);
  });

  test("every operation declares either a summary or an operationId", () => {
    const violations: string[] = [];
    eachOperation(spec, (path, method, op) => {
      if (!op.summary && !op.operationId) {
        violations.push(`${method.toUpperCase()} ${path}`);
      }
    });
    expect(violations).toEqual([]);
  });

  test("every operation declares at least one response", () => {
    const violations: string[] = [];
    eachOperation(spec, (path, method, op) => {
      if (!op.responses || Object.keys(op.responses).length === 0) {
        violations.push(`${method.toUpperCase()} ${path}`);
      }
    });
    expect(violations).toEqual([]);
  });

  test("every operation declares at least one 2xx response", () => {
    const violations: string[] = [];
    eachOperation(spec, (path, method, op) => {
      const responses = op.responses ?? {};
      const has2xx = Object.keys(responses).some((code) => code.startsWith("2"));
      if (!has2xx) {
        violations.push(`${method.toUpperCase()} ${path}`);
      }
    });
    expect(violations).toEqual([]);
  });
});

describe("OpenAPI spec — RFC 7807 error responses (#456 + #462)", () => {
  const spec = buildSpec(SPEC_OPTIONS);

  test("every declared 4xx/5xx response uses application/problem+json", () => {
    // Per #456: all error responses are RFC 7807 problem+json. The
    // spec must reflect that — anyone reverting to the legacy
    // `{ data, error }` envelope without updating the spec gets a
    // test failure here.
    //
    // Allowlist for paths whose error-shape predates #456 and is
    // tracked separately:
    const known4xxLegacy = new Set<string>([
      // (empty — #456 finished the migration; allowlist exists as a
      // forward-compat seam if a partial revert ever lands)
    ]);

    const violations: string[] = [];
    eachOperation(spec, (path, method, op) => {
      if (known4xxLegacy.has(`${method.toUpperCase()} ${path}`)) return;
      const responses = op.responses ?? {};
      for (const [code, body] of Object.entries(responses)) {
        if (!/^[45]/.test(code)) continue;
        const content = (body as { content?: Record<string, unknown> }).content;
        if (!content) continue; // some error responses are documented without a body shape
        // Accept either `application/problem+json` (#456 standard) or
        // legacy envelope IF the operation declares both. The bar is
        // "no error response that ONLY declares the legacy envelope".
        const types = Object.keys(content);
        const hasProblemJson = types.some((t) =>
          t.toLowerCase().includes("problem+json") || t.toLowerCase().includes("application/json"),
        );
        if (!hasProblemJson) {
          violations.push(`${method.toUpperCase()} ${path} ${code}: ${types.join(", ")}`);
        }
      }
    });
    expect(violations).toEqual([]);
  });
});

describe("OpenAPI spec — operation security declarations (#462)", () => {
  const spec = buildSpec(SPEC_OPTIONS);

  /**
   * Paths that are explicitly designed to be public (no auth). New
   * paths added here MUST be intentional — a route that should be
   * authenticated but ends up here is a CONVENTIONS.md §5 violation.
   *
   * Keep this list short and review-gated.
   */
  const publicPaths = new Set<string>([
    "/api/v1/skill-format/rules",
    "/api/v1/skill-manifest-schema.json",
  ]);

  test("every operation outside the public allowlist declares BearerAuth security", () => {
    const violations: string[] = [];
    eachOperation(spec, (path, method, op) => {
      if (publicPaths.has(path)) return;
      const sec = op.security as Array<Record<string, unknown[]>> | undefined;
      const hasBearer = Array.isArray(sec) && sec.some((s) => "BearerAuth" in s);
      if (!hasBearer) {
        violations.push(`${method.toUpperCase()} ${path}`);
      }
    });
    expect(violations).toEqual([]);
  });
});

describe("OpenAPI spec — schema reference integrity", () => {
  const spec = buildSpec(SPEC_OPTIONS);

  test("declared paths cover the foundational skill CRUD surface", () => {
    // This is a regression test, not a coverage test. The full
    // coverage gap (≈40 missing routes) is tracked as a follow-up on
    // #462. Here we just pin the routes that have been documented so
    // a refactor doesn't accidentally drop them.
    const required = [
      "/api/v1/skills",
      "/api/v1/skills/{idOrName}",
      "/api/v1/skills/{id}",
      "/api/v1/skill-search",
      "/api/v1/skill-format/rules",
      "/api/v1/skill-manifest-schema.json",
    ];
    const paths = spec.paths as Record<string, unknown>;
    const present = new Set(Object.keys(paths));
    const missing = required.filter((r) => !present.has(r));
    expect(missing).toEqual([]);
  });
});
