apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ornn-web-ingress
  namespace: ${NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: ornn.ornn-cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ornn-web
                port:
                  number: 80
