apiVersion: v1
kind: ConfigMap
metadata:
  name: chrono-storage-config
  namespace: ${NAMESPACE}
data:
  STORAGE_PORT: "${CHRONO_STORAGE_PORT}"
  S3_ENDPOINT: ${CHRONO_STORAGE_S3_ENDPOINT}
  S3_REGION: ${CHRONO_STORAGE_S3_REGION}
  S3_SIGNED_URL_EXPIRATION_SEC: "${CHRONO_STORAGE_S3_SIGNED_URL_EXPIRATION_SEC}"
  IDLE_TIMEOUT: "${CHRONO_STORAGE_IDLE_TIMEOUT}"
  LOG_LEVEL: ${CHRONO_STORAGE_LOG_LEVEL}
  LOG_PRETTY: "${CHRONO_STORAGE_LOG_PRETTY}"
  S3_AUTH_MODE: ${CHRONO_STORAGE_S3_AUTH_MODE}
